### ISSUE TITLE
Feature Request: Support folding range source code

### ISSUE THREAD

**Issue by wingyplus** [elixir-lsp/elixir_sense#108]
The original issue come from https://github.com/elixir-lsp/elixir-ls/issues/358, start from support do/end block would be good. Love to hear your feedback.

**NOTE:** I have a prototype version on ElixirLS that use `:elixir_tokenizer` here https://github.com/wingyplus/elixir-ls/commit/2d9a94ceb22147ab9c2e128cf029519f8bc0c758.

**Comment by axelson** [comment]
Code folding would be great to have! Although for the implementation it would be best to not rely on `:elixir_tokenizer` because it is a private elixir implementation detail and may change significantly between elixir versions (which would cause elixir_sense to break).

**Comment by wingyplus** [comment]
> Code folding would be great to have! Although for the implementation it would be best to not rely on `:elixir_tokenizer` because it is a private elixir implementation detail and may change significantly between elixir versions (which would cause elixir_sense to break).

@axelson I have recommended that uses `ElixirSense.Core.Normalized.Tokenizer` is better than using `:elixir_tokenizer` directly (refer to this comment https://github.com/elixir-lsp/elixir-ls/issues/358#issuecomment-680206762).  Love to see another way to do it. :)

**Comment by lukaszsamson** [comment]
Closing in favour of https://github.com/elixir-lsp/elixir-ls/pull/492
