### ISSUE TITLE
Provide first class support for type specs

### ISSUE THREAD

**Issue by msaraiva** [elixir-lsp/elixir_sense#11]
- [x] Autocomplete - Suggest available options for function arguments that are kw lists (options)
- [x] Autocomplete - Suggest types when in a module scope
- [x] Find documentation of types
- [x] Go to definition for types

**Comment by msaraiva** [comment]
In case anyone wants to take a look at it, I'm working on this branch: https://github.com/elixir-lsp/elixir_sense/tree/ms-improve-typespec-support

Here's a working example in VSCode:

![image](https://user-images.githubusercontent.com/457237/54078403-fccf6c80-42a5-11e9-964f-6d310f7bfda4.png)

**Comment by msaraiva** [comment]
Folks, I finished the main features I wanted for this one. There are a few adjustments to be made and some edge cases to treat. I hope you can find some time to test it before I publish it. Feedback is more than welcome.

By just updating ElixirSense you'll get "Go to definition" and "Hover" working for free with typespecs. For autocomplete of options and types, it will require changes in the editor's plugins to properly treat the new types of suggestion (`:param_option` and `:type_spec`).

Here's the commit on my fork that does this for ElixirLS: https://github.com/msaraiva/elixir-ls/commit/854221af8cc187e73e290658342d4851104e87d0

@axelson I'm not sure who will need to take action on the other projects to make the adjustments on the editor's plugins side so feel free to point this [branch](https://github.com/elixir-lsp/elixir_sense/tree/ms-improve-typespec-support) so they can test it.

@slashmili can you test this on vim?

If you want to see it in action, I published a small video showing off the new features.
https://twitter.com/MarlusSaraiva/status/1118661923455815680

Cheers!
-marlus

**Comment by axelson** [comment]
@msaraiva awesome! I've gotten it working locally with Spacemacs :)

Here is my branch that has your elixir-ls change, plus pulls in your `ms-improve-typespec-support` elixir_sense branch: https://github.com/axelson/elixir-ls/tree/better-type-specs

I think next steps are:
1. More testing
2. Create a PR on https://github.com/elixir-lsp/elixir_sense and then merge it after testing
3. Create a PR on https://github.com/elixir-lsp/elixir-ls that includes the elixir-ls change and bumps the elixir_sense version (pulling from the master branch)

**Comment by msaraiva** [comment]
> I've gotten it working locally with Spacemacs :)

@axelson nice! 

On twitter I've noticed that some people think that only VS Code will get these new features so I believe it would be nice to post some screenshots of them working on Spacemacs, Vim or any other editor to make sure people know that they can expect those changes in their prefered editor. WDYT?

Regarding the next steps, I Agree. I'm still testing and already found a couple of minor issues. I'll wait a few days so we can get more feedback and then I can create a PR.

Thanks!

**Comment by axelson** [comment]
> On twitter I've noticed that some people think that only VS Code will get these new features so I believe it would be nice to post some screenshots of them working on Spacemacs, Vim or any other editor to make sure people know that they can expect those changes in their prefered editor. WDYT?

Yeah, I'll make sure to post at least one screenshot :)

I tested the code a bit yesterday (along with https://github.com/elixir-lsp/elixir_sense/pull/10) and I got some extremely high CPU usage from the elixir-ls server. I'll try with a more minimal or no bumping of dependencies today to try to narrow down any potential issues.

**Comment by asummers** [comment]
@axelson I wonder if that was just it rebuilding the PLT.

**Comment by axelson** [comment]
That's what I thought at first, but I left it alone for an hour (over lunch), then when I came back after issuing a few commands the CPU usage was still very high and my editor became unresponsive.

**Comment by msaraiva** [comment]
Hi @axelson! Do you have any updates on the CPU usage issue? Is there anybody else facing the same problem? I can't reproduce it locally. Maybe I could help here if I get more information. Can you log the requests that are sent to ElixirSense and see if there's any kind of request that is been done multiple times in a short period of time? Maybe docs on hover? I have one last optimization to do on the "Go to definition" feature and I'm done. I'd love to be able to fix this CPU issue and release the new version this week. Let me know if you need anything.

Thanks!

**Comment by axelson** [comment]
I'll switch back to using the branch and try to get some debugging of what lsp messages were sent.

**Comment by msaraiva** [comment]
@axelson BTW, what's the best way to switch between the current version and a dev branch without messing up everything? I'm using VS Code to play with ElxirSense for the first time. Not sure I'm doing this the right way. What I do is just "Run/debug". That opens a whole new environment, which is great when I'm still developing. However, I would like to try out the new code on my "real" env and then have an easy way to "reset" to the old one in case of any issue comes up. Do you have any suggestions? 

Thanks!

**Comment by axelson** [comment]
@msaraiva you can test a new elixir-ls/elixir_sense by going to your local clone of https://github.com/JakeBecker/vscode-elixir-ls (the elixir-lsp fork isn't in a great state right now). Then in the `elixir-ls` directory add a remote for the elixir-lsp fork and checkout the commit that you want to use (I'm using https://github.com/axelson/elixir-ls/tree/better-type-specs).

Then:
* Run `vsce package` in root of project (this will generate a `.vsix` extension file)
* Open vscode
* Uninstall the elixir-ls extension
* Restart vscode (very important step! Without this you'll reinstall the old version again)
* Install the elixir-ls extension from the vsix file

Alternatively you should be able to run `code --install-extension elixir-ls-0.2.24.vsix` (but if you use this method it's important to not uninstall the extension first, otherwise you'll get the old extension version again).

Hope that helps!

**Comment by axelson** [comment]
@msaraiva Okay, I have confirmed an issue with the branch. Not sure if you'll be able to reproduce it. I've added you to a private repo that I'm having the problem on (check the bad-example2 branch).

The last sent message was this:
```
Content-Length: 487

{
  "jsonrpc": "2.0",
  "method": "textDocument/didChange",
  "params": {
    "textDocument": {
      "uri": "file:///home/jason/dev/ls_proxy/app/config/prod.exs",
      "version": 1
    },
    "contentChanges": [
      {
        "range": {
          "start": {
            "line": 28,
            "character": 20
          },
          "end": {
            "line": 28,
            "character": 20
          }
        },
        "rangeLength": 0,
        "text": "r"
      }
    ]
  }
}
```

It seems to be related to autocomplete. I get the issue on https://github.com/axelson/elixir-ls/tree/better-type-specs but not on https://github.com/elixir-lsp/elixir-ls/tree/master

Right now it is reproducible for me 100% on one of my computers, will try on others later. The symptoms are high CPU usage and rapidly growing memory. On linux it eventually causes the computer to become very unresponsive. Possibly an infinite loop is being triggered?

**Comment by msaraiva** [comment]
@axelson awesome! I'll address this issue this week so we can release a new version. Thank you so much for this and also for the detailed instructions on testing ElixirSense on VSCode. Extremely helpful!

**Comment by msaraiva** [comment]
Hey @axelson! I just pushed a couple of fixes to master including a fix for the CPU issue. Please, let me know if you find any other issue.

**Comment by axelson** [comment]
@msaraiva Thanks for this! Will test it out in https://github.com/elixir-lsp/elixir-ls/pull/38

Also I'm a little curious. What was the fix for the CPU usage issue? I'm not noticing anything in the commit list.

**Comment by msaraiva** [comment]
@axelson This bad boy [here](https://github.com/elixir-lsp/elixir_sense/commit/3faac98c402b8a402adac99fe6c94c176616dadd). There are situations where `module` is `nil` which was causing the function to call itself again and again, forever. One of those situations is when you had heredocs.

**Comment by axelson** [comment]
Ah, I see. Good catch!
