### ISSUE TITLE
Failure with last Elixir upgrade (1.12.0-dev)

### ISSUE THREAD

**Issue by henrythebuilder** [elixir-lsp/elixir_sense#112]
Hi,
after upgrading Elixir, probably from [df04a2d](https://github.com/elixir-lang/elixir/commit/df04a2d53b19746746c4d9d1ade62e5b3d128413) (also reported on branch 1.11),  ElixirLS fail to start (via eglot) due to a missing function/signature in ElixirSense.

I'm using Emacs+eglot+ElixirLS in a Debian system with Erlang 23 and Elixir aligned to master branch (1.12.0-dev)

Back to the code ElixirSense project test fails with the same origin:

```
** (FunctionClauseError) no function clause matching in ElixirSense.Core.Normalized.Code.extract_docs/1

     The following arguments were given to ElixirSense.Core.Normalized.Code.extract_docs/1:
     
         # 1
         %{}
     
     Attempted function clauses (showing 3 out of 3):
     
         defp extract_docs(%{"en" => docs_en})
         defp extract_docs(:hidden)
         defp extract_docs(:none)
```

Trying to change `ElixirSense.Core.Normalized.Code.extract_docs/1` with:

```
diff --git a/lib/elixir_sense/core/normalized/code.ex b/lib/elixir_sense/core/normalized/code.ex
index 8659bf5..c9eec83 100644
--- a/lib/elixir_sense/core/normalized/code.ex
+++ b/lib/elixir_sense/core/normalized/code.ex
@@ -68,7 +68,7 @@ defp map_doc_entry({{kind, name, arity}, anno, signatures, docs, metadata}) do
           String.t() | false | nil
   defp extract_docs(%{"en" => docs_en}), do: docs_en
   defp extract_docs(:hidden), do: false
-  defp extract_docs(:none), do: nil
+  defp extract_docs(_), do: nil
 
   defp get_fun_docs(module, docs) do
     docs_from_module =
```

ElixirLS seam to work fine but two test on ElixirSense still fail:
- `test retrieve function documentation from behaviour if available (ElixirSense.DocsTest)`
- `test retrieve macro documentation from behaviour if available (ElixirSense.DocsTest)`

My original intention was to offer a complete solution as a pull-request but at the moment, given even the two failed tests, I still wanted to get involved with something useful.

Enrico

**Comment by lukaszsamson** [comment]
Please note that development and release candidate versions of elixir are not officially supported due to massive breaking changes

**Comment by henrythebuilder** [comment]
ok, I understand, in fact the problem came out due to the latest changes.
Let's see how it evolves until the release of Elixir.
Thanks anyway for the support and for your work on `elixir-lsp`

**Comment by henrythebuilder** [comment]
Thanks :+1:
