### ISSUE TITLE
Ecto plugin misses completion for fields

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir_sense#116]
I've gotten at least one other report of this. And here's a particular repo where I'm seeing it:

https://github.com/hui-ad/institute/blob/73bb59c1d64d304065019e228fe92d72d48b50e0/apps/institute/lib/institute/meetings.ex#L22

Then add the following line:
```
q2 = from e in Institute.Schedule.Event,
    where: e.|
```
(The `|` represents the cursor). I'd expect to get a list of fields but instead no completion is returned.

**Comment by msaraiva** [comment]
@axelson it should be working now. Thanks for reporting this issue!

**Comment by axelson** [comment]
Great! Thanks for the quick fix.
