### ISSUE TITLE
More fuzzy matching

### ISSUE THREAD

**Issue by princemaple** [elixir-lsp/elixir_sense#122]
Potential candidates

- [x] lib/elixir_sense/plugins/option.ex
- [x] lib/elixir_sense/providers/suggestion/reducers/type_specs.ex
- [x] lib/elixir_sense/providers/suggestion/reducers/callbacks.ex
- [x] lib/elixir_sense/providers/suggestion/reducers/struct.ex
- [x] lib/elixir_sense/providers/suggestion/reducers/params.ex
- [x] lib/elixir_sense/providers/suggestion/reducers/overridable.ex
- [x] lib/elixir_sense/providers/suggestion/reducers/protocol.ex
- [x] lib/elixir_sense/providers/suggestion/reducers/docs_snippets.ex
- [x] lib/elixir_sense/providers/suggestion/complete.ex
- [x] lib/elixir_sense/plugins/ecto/schema.ex

@lukaszsamson commented in https://github.com/elixir-lsp/elixir_sense/pull/121#issuecomment-779491652:
> Let's do them in follow up PRs. This one is already big. I'm not sure if callbacks, overridable and protocols are good candidates. Apart from those I'd include more suggestions from complete module: elixir/erlang modules, variables, attributes, map/struct keys. Elixir modules would probably work better with some letter downcasing.

**Comment by maciej-szlosarczyk** [comment]
lib/elixir_sense/plugins/option.ex is done in #128 
 lib/elixir_sense/providers/suggestion/reducers/struct.ex and  lib/elixir_sense/providers/suggestion/reducers/type_specs.ex
 in #129.

**Comment by princemaple** [comment]
Some notes about working on fuzzy matching.

- There might be test failing because of fuzzy matching in ElixirLS and need to be fixed. See this PR for reference: https://github.com/elixir-lsp/elixir-ls/pull/491
  - basically just need to bump elixir_sense in elixir-ls and fix tests
- There are some inconsistent behavior around module name matching in ecto related code and non-ecto code. Might be something to keep in mind when working on module names.

**Comment by lukaszsamson** [comment]
I went ahead and added fuzzy matching in complete and ecto. There was also some gaps in type_specs not covered in #129. I needed some tweaking of the matching algorithm to play nicely with elixir aliases (see https://github.com/elixir-lsp/elixir_sense/commit/9b5c8c417cc87878cc9ff06c8dac97cce21007b1#diff-da7b9c8d53d3b60dfe4be57ab5edea9ebfcb6fcd2d8b1e263c923e9bd8ae8a65R448). Anyway this means that fuzzy matching is used in all relevant places.
