### ISSUE TITLE
[Proposal] Drop server functionality

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lsp/elixir_sense#135]
Let's be frank. I don't know of a single active user of ElixirSense server. All relevant IDEs/editors have long migrated to language server. In the last 3 years there were only 2 issues reported and no contributions. Maintaining it adds an unnecessary burden - run.exs is not covered by tests and needs tweaking on every module addition/refactoring. Server tests are flaky and crash when other tests do IO. It makes debugging more complicated. I know it could be changed into a proper application (vide elixir-lsp apps). I know it could be extracted to a separate library. I just don't see there's a need for it any more. @msaraiva please voice your opinion.

**Comment by msaraiva** [comment]
> I know it could be extracted to a separate library. I just don't see there's a need for it any more.

@lukaszsamson I strongly agree. If there are still people using it, they can fork or move it to a separate project and maintain it as they wish. It makes no sense to keep it in the context of this project anymore.

**Comment by axelson** [comment]
:+1: from me as well

**Comment by slashmili** [comment]
@lukaszsamson you probably should  remove `run.exs`and update [README.md](https://github.com/elixir-lsp/elixir_sense#usage)
if I follow the readme:
```
elixir run.exs unix 0 dev
** (Code.LoadError) could not load /private/tmp/elixir_sense/lib/elixir_sense/server.ex
    (elixir 1.12.3) lib/code.ex:1807: Code.find_file/2
    (elixir 1.12.3) lib/code.ex:1254: Code.require_file/2
    (elixir 1.12.3) lib/enum.ex:930: Enum."-each/2-lists^foreach/1-0-"/2
    run.exs:40: (file)
```
