### ISSUE TITLE
Feature Request: Get the modules defined in a given file

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir_sense#142]
In the ElixirLS debugger it would be very helpful to get the list of modules defined in a file. This would allow the user to only interpret some of the modules in their project instead of all modules of the system. Defining by filename would be a more natural interface than a list of module names.

Related ElixirLS issue: https://github.com/elixir-lsp/elixir-ls/issues/615

Although after thinking about it in #615 I opted to go with a regex based on the module name I still think that this could be a useful feature for ElixirSense to have.

**Comment by lukaszsamson** [comment]
No need to add it to elixir_sense as it's doable with pure elixir/OTP code. Debugger now uses that as a fallback
```
:code.all_loaded()
        |> Enum.map(&elem(&1, 0))
        |> Enum.filter(fn module -> String.starts_with?(Atom.to_string(module), "Elixir.") end)
        |> Enum.group_by(fn module ->
          module_info = ModuleInfoCache.get(module) || module.module_info()
          Path.expand(to_string(module_info[:compile][:source]))
        end)
```
Besides, the original issue is now closed and I don't think there's much need for implementing path based exclusions
