### ISSUE TITLE
`no case clause matching` in `ElixirSense.Core.Normalized.Tokenizer.do_tokenize_1_7/1`

### ISSUE THREAD

**Issue by cr0t** [elixir-lsp/elixir_sense#148]
Hello,

I apologize if that is a known issue, but I tried all the latest versions of packages, and it didn't help. I've noticed an issue in vim, but it led me to ElixirSense codebase. Not sure how this is relevant.

I was trying to configure my vim environment and set up code autocompletion/suggestions (with https://github.com/neoclide/coc.nvim plugin), but it is failing to show suggestions and documentation while I'm typing the code.

When I ran `:CocCommand workspace.showOutput` it shows errors in the ElixirSense when vim attempts to show autosuggestion dropdown.

Thanks in advance if it's relevant and can be fixed on your side. Sorry, if it's not relevant.

### `coc.nvim`'s output

```
[Error  - 4:12:18 PM] Request textDocument/completion failed.
  Message: an exception was raised:
    ** (CaseClauseError) no case clause matching: {:error, {4, 6, ['missing terminator: end (for "do" starting at line 2)', []], []}, [], [], [{:alias, {4, 5, nil}, :S}, {:eol, {3, 31, 1}}, {:")", {3, 30, nil}}, {:bin_string, {3, 27, nil}, ["a"]}, {:",", {3, 25, 0}}, {:bin_string, {3, 22, nil}, ["s"]}, {:"(", {3, 21, nil}}, {:paren_identifier, {3, 12, nil}, :contains?}, {:., {3, 11, nil}}, {:alias, {3, 5, nil}, :String}, {:eol, {2, 18, 1}}, {:do, {2, 16, nil}}, {:")", {2, 14, nil}}, {:identifier, {2, 12, nil}, :_a}, {:"(", {2, 11, nil}}, {:paren_identifier, {2, 7, nil}, :test}, {:identifier, {2, 3, nil}, :def}, {:eol, {1, 24, 1}}, {:do, {1, 22, nil}}, {:alias, {1, 17, nil}, :Test}, {:., {1, 16, nil}}, {:alias, {1, 11, nil}, :Lexin}, {:identifier, {1, 1, nil}, :defmodule}]}
        (elixir_sense 2.0.0) lib/elixir_sense/core/normalized/tokenizer.ex:16: ElixirSense.Core.Normalized.Tokenizer.do_tokenize_1_7/1
        (elixir_sense 2.0.0) lib/elixir_sense/core/source.ex:492: ElixirSense.Core.Source.which_func/2
        (elixir_sense 2.0.0) lib/elixir_sense/plugins/util.ex:54: ElixirSense.Plugins.Util.partial_func_call/3
        (elixir_sense 2.0.0) lib/elixir_sense/plugins/util.ex:71: ElixirSense.Plugins.Util.func_call_chain/4
        (elixir_sense 2.0.0) lib/elixir_sense/providers/suggestion/generic_reducer.ex:31: ElixirSense.Providers.Suggestion.GenericReducer.reduce/6
        (elixir 1.13.1) lib/enum.ex:4475: Enumerable.List.reduce/3
        (elixir 1.13.1) lib/enum.ex:2442: Enum.reduce_while/3
        (elixir_sense 2.0.0) lib/elixir_sense/providers/suggestion.ex:112: ElixirSense.Providers.Suggestion.find/4
  Code: -32000 

16:12:18.328 [error] Process #PID<0.1307.0> raised an exception
** (CaseClauseError) no case clause matching: {:error, {4, 6, ['missing terminator: end (for "do" starting at line 2)', []], []}, [], [], [{:alias, {4, 5, nil}, :S}, {:eol, {3, 31, 1}}, {:")", {3, 30, nil}}, {:bin_string, {3, 27, nil}, ["a"]}, {:",", {3, 25, 0}}, {:bin_string, {3, 22, nil}, ["s"]}, {:"(", {3, 21, nil}}, {:paren_identifier, {3, 12, nil}, :contains?}, {:., {3, 11, nil}}, {:alias, {3, 5, nil}, :String}, {:eol, {2, 18, 1}}, {:do, {2, 16, nil}}, {:")", {2, 14, nil}}, {:identifier, {2, 12, nil}, :_a}, {:"(", {2, 11, nil}}, {:paren_identifier, {2, 7, nil}, :test}, {:identifier, {2, 3, nil}, :def}, {:eol, {1, 24, 1}}, {:do, {1, 22, nil}}, {:alias, {1, 17, nil}, :Test}, {:., {1, 16, nil}}, {:alias, {1, 11, nil}, :Lexin}, {:identifier, {1, 1, nil}, :defmodule}]}
    (elixir_sense 2.0.0) lib/elixir_sense/core/normalized/tokenizer.ex:16: ElixirSense.Core.Normalized.Tokenizer.do_tokenize_1_7/1
    (elixir_sense 2.0.0) lib/elixir_sense/core/source.ex:492: ElixirSense.Core.Source.which_func/2
    (elixir_sense 2.0.0) lib/elixir_sense/plugins/util.ex:54: ElixirSense.Plugins.Util.partial_func_call/3
    (elixir_sense 2.0.0) lib/elixir_sense/plugins/util.ex:71: ElixirSense.Plugins.Util.func_call_chain/4
    (elixir_sense 2.0.0) lib/elixir_sense/providers/suggestion/generic_reducer.ex:31: ElixirSense.Providers.Suggestion.GenericReducer.reduce/6
    (elixir 1.13.1) lib/enum.ex:4475: Enumerable.List.reduce/3
    (elixir 1.13.1) lib/enum.ex:2442: Enum.reduce_while/3
    (elixir_sense 2.0.0) lib/elixir_sense/providers/suggestion.ex:112: ElixirSense.Providers.Suggestion.find/4
[Error  - 4:12:22 PM] Request textDocument/completion failed.
  Message: an exception was raised:
    ** (CaseClauseError) no case clause matching: {:error, {4, 12, ['missing terminator: end (for "do" starting at line 2)', []], []}, [], [], [{:., {4, 11, nil}}, {:alias, {4, 5, nil}, :String}, {:eol, {3, 31, 1}}, {:")", {3, 30, nil}}, {:bin_string, {3, 27, nil}, ["a"]}, {:",", {3, 25, 0}}, {:bin_string, {3, 22, nil}, ["s"]}, {:"(", {3, 21, nil}}, {:paren_identifier, {3, 12, nil}, :contains?}, {:., {3, 11, nil}}, {:alias, {3, 5, nil}, :String}, {:eol, {2, 18, 1}}, {:do, {2, 16, nil}}, {:")", {2, 14, nil}}, {:identifier, {2, 12, nil}, :_a}, {:"(", {2, 11, nil}}, {:paren_identifier, {2, 7, nil}, :test}, {:identifier, {2, 3, nil}, :def}, {:eol, {1, 24, 1}}, {:do, {1, 22, nil}}, {:alias, {1, 17, nil}, :Test}, {:., {1, 16, nil}}, {:alias, {1, 11, nil}, :Lexin}, {:identifier, {1, 1, nil}, :defmodule}]}
        (elixir_sense 2.0.0) lib/elixir_sense/core/normalized/tokenizer.ex:16: ElixirSense.Core.Normalized.Tokenizer.do_tokenize_1_7/1
        (elixir_sense 2.0.0) lib/elixir_sense/core/source.ex:492: ElixirSense.Core.Source.which_func/2
        (elixir_sense 2.0.0) lib/elixir_sense/plugins/util.ex:54: ElixirSense.Plugins.Util.partial_func_call/3
        (elixir_sense 2.0.0) lib/elixir_sense/plugins/util.ex:71: ElixirSense.Plugins.Util.func_call_chain/4
        (elixir_sense 2.0.0) lib/elixir_sense/providers/suggestion/generic_reducer.ex:31: ElixirSense.Providers.Suggestion.GenericReducer.reduce/6
        (elixir 1.13.1) lib/enum.ex:4475: Enumerable.List.reduce/3
        (elixir 1.13.1) lib/enum.ex:2442: Enum.reduce_while/3
        (elixir_sense 2.0.0) lib/elixir_sense/providers/suggestion.ex:112: ElixirSense.Providers.Suggestion.find/4
  Code: -32000 
```

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/113878/148242793-b3d3e7e5-3663-4946-b5c9-d6b27c7b28bf.png">

**Comment by lukaszsamson** [comment]
Please provide sample code that reproduces this. Also provide your elixir and otp version and elixir-ls version

**Comment by cr0t** [comment]
Hey @lukaszsamson,

I am not sure that I can provide you a snippet to reproduce it easily, but I've done some tests on my machine and let me show what I've got; I have a hunch that the error might be related to Elixir 1.13.

First, my setup is this: nvim (v0.6.1), coc.nvim plugin, and asdf (v0.9.0); and I've created a simple test project (`mix new lsp_test`), entered the project directory, and put `elixir 1.12.3` into `.tools_version` file in the root of this directory.

Then I ran nvim and opened `mix.exs` to let it run LSP and build its files.

After a minute or so, I tried to type in `String.downcase` and got instant suggestions (+ mini-documentation) in the popup, including all the available methods for `String` module. See the `:CocCommand workspace.showOutput` here:

<img width="2032" alt="Screen Shot 2022-01-06 at 16 29 33" src="https://user-images.githubusercontent.com/113878/148408642-8b97d429-06e9-4f00-af32-3ad4fc022d2a.png">

Then I switched my Elixir version in the `.tool-versions` file to `elixir 1.13.1-otp-24`, removed `.elixir_ls` directory and restart nvim.

I tried the same – typed in `String.downca...` and got nothing in the suggestions. `:CocCommand workspace.showOutput` shows this:

<img width="2032" alt="Screen Shot 2022-01-06 at 16 34 04" src="https://user-images.githubusercontent.com/113878/148408955-eccb1364-a88f-445a-8395-bedc1347cb50.png">

## 1.13 vs. 1.12?

So, I had the same codebase, the same setup, the only difference - Elixir versions. With 1.13.1 ElixirSense gives cov.nvim plugin an `CaseClauseError` exception.

P.S. Would these steps be enough for you to reproduce the issue, or I should try to do something else?
P.P.S. I am not running ElixirSense directly – it's done by the chain of my editor+plugins, and I am not sure how relevant this to the library itself. But, as you can see from the reproduction procedure above, it might be affected by Elixir version.

**Comment by lukaszsamson** [comment]
You are using elixir-ls 0.7.0 which is not compatible with elixir 1.13. Please upgrade to 0.9
