### ISSUE TITLE
Absinthe autocompletions doesnt work

### ISSUE THREAD

**Issue by kasvith** [elixir-lsp/elixir_sense#157]
Since Absinthe uses macros heavily, Elixir-Sense doesn't do proper autocompletion.
A custom plugin like below will help resolving this problem as mentioned

https://github.com/elixir-lsp/elixir-ls/issues/193#issuecomment-1019431983

**Comment by gugahoa** [comment]
@lukaszsamson do you mind mentoring me on how to do it? Just a few pointers should be enough

**Comment by Matsa59** [comment]
@gugahoa I just start for phoenix (only scope for the moment). It's not so hard. Look how the plugin for ecto works. 

Basically you have to implement the function suggestion defined by the behavior ElixirSense.Plugin (or something like that, sorry I'm on my phone).

Then it's about text and data manipulation

**Comment by lukaszsamson** [comment]
Closing as this is not en elixir_sense issue
