### ISSUE TITLE
Some questions about References

### ISSUE THREAD

**Issue by scottming** [elixir-lsp/elixir_sense#202]
Hi, @lukaszsamson  I've been exploring this [recode](https://github.com/hrzndhrn/recode) repository lately, and it's a nice little library that's built on [sourceror](https://github.com/doorgan/sourceror/blob/main/lib/sourceror.ex).

I want to implement this feature in the next days: [list all public functions not used in other modules](https://github.com/hrzndhrn/recode/issues/36)

But it presupposes a stable references API, and I noticed that elixir-sense's references have always had some shortcomings, like in test directories or using `use` keyword to import, etc., and I also saw that you are going to [deprecate](https://github.com/elixir-lsp/elixir_sense/issues/166) this repository.

So I'd like to re-implement a reference API based on sourceror AST traversal, and I'd love to hear your suggestions.

**Comment by lukaszsamson** [comment]
Currently references provider relies on AST only in a limited way - it uses AST metadata to guess what symbol (fun/module/var/attribute) is currently under the cursor. elixir_sense understands most of the standard elixir AST, it's able to extract modules, funs, expand aliases, imports and to some degree `use` macros. It has no understanding of macro heavy code though.

The actual finding of function references depends on a trace data passed from elixirLS tracer. This trace data is accurate (up to dynamic remote calls which cannot be traced statically at compile time). It's also limited to compiled code - `.exs` tests are an obvious exception here.

In your case I'd start with a compile tracer (elixirLS already has one) and some way of getting function metadata (possibly using elixir_sense MetadataBuilder or sth custom) for the current file. Matching those should prodoce a list of public symbols that could be made private

Regarding the library - I plan to move the providers to elixirLS repo and merge them with LSP provider implementations leaving here only the building blocks.
