### ISSUE TITLE
Crash in docs provider on keyword

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lsp/elixir_sense#226]
** (FunctionClauseError) no function clause matching in ElixirSense.Core.SurroundContext.to_binding/2
    (elixir_sense 2.0.0) lib/elixir_sense/core/surround_context.ex:6: ElixirSense.Core.SurroundContext.to_binding({:keyword, 'do'}, A)
    (elixir_sense 2.0.0) lib/elixir_sense/providers/docs.ex:32: ElixirSense.Providers.Docs.all/4
    (elixir_sense 2.0.0) lib/elixir_sense.ex:75: ElixirSense.docs/3
    (language_server 0.14.5) lib/language_server/providers/hover.ex:24: ElixirLS.LanguageServer.Providers.Hover.hover/4
    (language_server 0.14.5) lib/language_server/server.ex:824: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2

**Comment by Goose97** [comment]
Fixed by https://github.com/elixir-lsp/elixir_sense/commit/64966194bb144741ef03f0a2e9d777b8fe132085

I think we can close this?
