### ISSUE TITLE
Elixir proxy completion adds alias

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lsp/elixir_sense#230]
When completing `Elixir`, `Elixir` proxy module is suggested with alias to insert. The are 2 `Elixir` entries.

<img width="629" alt="Screenshot 2023-07-03 at 17 05 41" src="https://github.com/elixir-lsp/elixir_sense/assets/1078186/219bf592-316b-4cee-a406-84ef07e2a808">

**Comment by Goose97** [comment]
Can you give some description about this issue?

**Comment by lukaszsamson** [comment]
@Goose97 updated
