### ISSUE TITLE
Better support for .eex files ~E and ~L

### ISSUE THREAD

**Issue by msaraiva** [elixir-lsp/elixir_sense#25]
It seems that the following doesn't work when in a `.eex` files, `~E` or `~L`:

  * SIgnature
  * Docs
  * Suggestions for variables defined inside the template

**Comment by kenny-evitt** [comment]
I'm using ElixirSense via [alchemist.vim](https://github.com/slashmili/alchemist.vim) and I opened an issue on its GitHub project related to this:

 - [ExDoc and ExDef for functions (or modules) in Embedded Elixir files · Issue #155 · slashmili/alchemist.vim](https://github.com/slashmili/alchemist.vim/issues/155)

... but I didn't think it was possible, or feasible, given that the context in which an *.eex* template file is evaluated doesn't seem to be closely coupled to the file.

But I'm glad I seem to have been wrong!

**Comment by msaraiva** [comment]
@kenny-evitt regarding `~E` and `~L` it's totally doable. However, you're right about `.eex` files. They can be "injected" in any file. Maybe, the best we could do would be to try to find the related view based on the folder/name of the template. But then it would not work when the developer does not follow the convention.

@axelson @lukaszsamson WDYT?

**Comment by kenny-evitt** [comment]
@msaraiva Maybe, for *.eex* files, the commands, or new similar commands, could accept both a line and column in the *.eex* file and a line and column in the relevant 'view' module file. The new commands could be named `EexDoc` and `EexDef`.

**Comment by axelson** [comment]
Yeah for plain `~E` and `~L` I think that they could be used in multiple contexts so it's impossible to know how it's going to be used. I do like what @kenny-evitt suggested, that seems like a practical compromise which will help in the majority of cases.

**Comment by lukaszsamson** [comment]
SIgnature and docs definitely work in (h)eex

**Comment by lukaszsamson** [comment]
Vars in templates tracked in https://github.com/elixir-lsp/vscode-elixir-ls/issues/279
