### ISSUE TITLE
Release v2.0.0

### ISSUE THREAD

**Issue by msaraiva** [elixir-lsp/elixir_sense#26]
I think it's time to publish a new release since we already have some nice new features and a bunch of fixes/improvements. Unless any of you has something else in mind, I'm planning to to this after #20, #25  and #24 are implemented and merged.

/cc @axelson, @@lukaszsamson

**Comment by axelson** [comment]
Sounds good to me! There's been a bunch of improvements. Although if there aren't any breaking changes the new version could just be 1.1.0.

**Comment by lukaszsamson** [comment]
I'm currently working on better support for protocols. I plan to finish it in a few days.
@axelson I'm not sure if there are going to be any breaking changes. My PRs were mostly bugfixes and new features. Elixir ecosystem does not show much appreciation to semver anyway.

**Comment by msaraiva** [comment]
There should be no breaking changes for clients using only the `ElixirSense` module. However, I can confirm at least one breaking change regarding ElixirLS, which uses `Introspection` directly, as stated here https://github.com/elixir-lsp/elixir_sense/issues/20#issue-474096673. So maybe v2.0.0 makes sense.

**Comment by lukaszsamson** [comment]
@axelson do you have elixir-lsp organization hex.pm credentials? @msaraiva I know you published 1.0 from your personal account

**Comment by axelson** [comment]
@lukaszsamson there isn't an elixir-lsp organization. I don't think hex.pm generally uses organizations for this, according to the `mix hex.organization` docs, organizations are for managing private packages. I think what we probably want to do is ask @msaraiva to add you as an owner to https://hex.pm/packages/elixir_sense

**Comment by msaraiva** [comment]
@lukaszsamson yeah, I need to add you as owner. What's your username on hex?

**Comment by lukaszsamson** [comment]
> What's your username on hex?

@msaraiva lukaszsamson

**Comment by lukaszsamson** [comment]
> > What's your username on hex?
> 
> @msaraiva lukaszsamson

ping @msaraiva
