### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lsp/elixir_sense#27]
This library is currently licensed under MIT license but it contains code taken from alchemist-server project licensed under GPL v3:
- `lib/alchemist/helpers/complete.ex`
- `lib/alchemist/helpers/module_info.ex` and  `test/alchemist/helpers/module_info_test.exs`

The status of `lib/alchemist/helpers/complete.ex` is even more complicated as it is in fact a derrived work basing on elixir `lib/iex/lib/iex/autocomplete.ex` covered by Apache License v2 and copyrighted by Platformatec and it's not likely that alchemist-server authors had Platformatec's agreement to relicense it under GPL v3. AFAIK modifications to Apache Licensed  code can be released under GPL v3, but the not modified part stays under original license.

What needs to be done:
1. obtain alchemist-server's authors' agreement to relicense under MIT or rewrite GPL covered code or mention that the files are licensed under GPL v3 (I'm not sure if it's doable to release this lib under part MIT part GPL v3 license)
2. adhere to Apache License requirements with (`lib/alchemist/helpers/complete.ex` and also `test/alchemist/helpers/complete_test.exs`), i.e. mention that original parts are copyrighted and licensend under Apache License and include list of modifications and required notices.

**Comment by Trevoke** [comment]
@tonini Hello! We need your authorization and help for some legal things here :)

**Comment by msaraiva** [comment]
There are other cases like `lib/elixir_sense/core/introspection.ex` which also includes code from `elixir-lang/elixir` and `elixir-lang/ex_doc`. We should definitely adhere to Apache License and regarding `complete.ex`, my plan is to rewrite it from scratch as already mentioned [here](https://github.com/elixir-lsp/elixir_sense/pull/24#discussion_r311733578).

**Comment by msaraiva** [comment]
Regarding any code copyrighted by Plataformatec, we just have to add a license note at the top of the file. Like this: https://github.com/elixir-lsp/elixir_sense/commit/3de6b52f977add9e5554ddd70510e4570d15c5f6

**Comment by lukaszsamson** [comment]
Since Alchemist author was not responsive I went ahead and removed all GPL licensed code in 871571a61cb3189dc15709d9c61eccda76e8a5d8 and 371347669c3bc162b2a1de5fac94fb18ff7891e0. All Platformatec copyrighted code now also has proper disclaimers and readme points to original work.
