### ISSUE TITLE
Document that this is included in elixir-ls

### ISSUE THREAD

**Issue by iloveitaly** [elixir-lsp/elixir_sense#276]
this was not clear to me as an elixir newcomer.

**Comment by lukaszsamson** [comment]
Isn't that sufficient?
https://github.com/elixir-lsp/elixir-ls/blob/master/README.md#acknowledgements-and-related-projects

**Comment by iloveitaly** [comment]
Yes, but in my case I ran into elixir_sense _first_ and wasn't aware of the other repo.
