### ISSUE TITLE
Server listens to a new sock after a client joins

### ISSUE THREAD

**Issue by slashmili** [elixir-lsp/elixir_sense#53]
I have a strange issue, I don't know if it's only for me or you also have the same problem but haven't noticed it.

![Screenshot 2019-10-19 at 00 40 01](https://user-images.githubusercontent.com/585764/67132467-3b98ae00-f209-11e9-8a23-05ecaa32c3ae.png)

1. I run server using 
```
elixir run.exs unix 0 dev
```
2. Start an iex console and copy paste [the example](https://github.com/elixir-lsp/elixir_sense/blob/master/README.md#example-using-gen_tcp) in README
```
{:ok, socket} = 
...
data = :erlang.term_to_binary(request)
:ok = :gen_tcp.send(socket, data)
{:ok, response} = :gen_tcp.recv(socket, 0)
:erlang.binary_to_term(response)
```

3. By this time I see in the output of my server that it listens to a new sock file. 

4. I did try to to connect to the old sock but it's not available anymore
```
Interactive Elixir (1.9.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> {:ok, socket} = :gen_tcp.connect({:local, '/var/folders/h8/xlzsrqld6rldv_l03dsn60x80000gn/T/elixir-sense-1571438027826601476.sock'}, 0, [:binary, active: false, packet: 4])
** (MatchError) no match of right hand side value: {:error, :econnrefused}
    (stdlib) erl_eval.erl:453: :erl_eval.expr/5
    (iex) lib/iex/evaluator.ex:257: IEx.Evaluator.handle_eval/5
    (iex) lib/iex/evaluator.ex:237: IEx.Evaluator.do_eval/3
    (iex) lib/iex/evaluator.ex:215: IEx.Evaluator.eval/3
    (iex) lib/iex/evaluator.ex:103: IEx.Evaluator.loop/1
    (iex) lib/iex/evaluator.ex:27: IEx.Evaluator.init/4
```

**Comment by lukaszsamson** [comment]
Closing as the server is removed (see #135)
