### ISSUE TITLE
Extend CI test matrix

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lsp/elixir_sense#60]
Currently the tests are run only on elixir 1.9. I did an experiment on my fork with Github Actions. I set up a matrix and with some ifs added the test suite passes on 1.9, 1.8 and 1.7. Making 1.6 work would take too much effort and I think it's time we dropped support (or maybe when 1.10 is released).
https://github.com/lukaszsamson/elixir_sense/runs/308785248
Anyway I think we should introduce testing on more than one version.
@msaraiva @axelson WDYT?

**Comment by lukaszsamson** [comment]
https://github.com/elixir-lsp/elixir_sense/issues/91 has to be addressed first

**Comment by axelson** [comment]
I agree that this would be a good change

**Comment by msaraiva** [comment]
Would it be a good idea to start moving only the failing tests on 1.10.1? And then on every new version, if we have more tests failing, we address them individually until we get all (most) of them done. I mean, I'm not sure yet how long it would take to address all of them at once.

**Comment by lukaszsamson** [comment]
CI now runs tests on elixir 1.7-1.10 and otp 19-22. I made it not required to pass all tests on < 1.9. It does not give a full certainty but at least we can see if the code is not terribly broken.
