### ISSUE TITLE
New project under elixir-lsp to support Surface

### ISSUE THREAD

**Issue by msaraiva** [elixir-lsp/elixir_sense#63]
Hi @axelson, @asummers and anyone interested.

I'm working on a new open-source project called `Surface` that should become public in the next couple of days. You can see it in action [here](http://surface-demo.msaraiva.io/). The main goal is to provide a standard way to create and reuse components in Phoenix/LiveView with exceptional integration with editors and other tools.

Having that in mind, I created a VS Code extension to add support for syntax highlighting and I believe it would be great if the project could stay under the `elixir-lsp` umbrella. The extension can be found at https://github.com/msaraiva/vscode-surface. 

I also have some ideas listed at the end of the [Getting Started](http://surface-demo.msaraiva.io/getting_started) to improve developer experience by customizing ElixirSense. @lukaszsamson let me know what you think.

Cheers.

-marlus

**Comment by axelson** [comment]
That looks like very promising project! I think it would be great to keep the vscode portion under the `elixir-lsp` umbrella (even if it isn't directly using lsp). It would probably also make sense to publish the vscode extension under the elixir-lsp vscode publisher (I'd be glad to add you to the publisher, although it may be a bit of a manual process involving their support).

Some other thoughts/questions:
* How feasible/how much work would it take to add the `Surface` support to vscode-elixir-ls? (I really don't have a handle on the work involved)
* Is there a way to ensure that vscode-surface is discoverable to users using Surface (besides the surface or vscode-surface docs). VSCode has a nice prompt that comes up when you first open an Elixir file and don't have any extensions that handle `.ex`. Perhaps something similar could be added to vscode-elixir-ls that would suggest vscode-surface the first time you open a Surface file.

cc: @Trevoke

**Comment by msaraiva** [comment]
> I think it would be great to keep the vscode portion under the elixir-lsp umbrella (even if it isn't directly using lsp)

Yeah. That's exactly what I think.

> It would probably also make sense to publish the vscode extension under the elixir-lsp vscode publisher (I'd be glad to add you to the publisher, although it may be a bit of a manual process involving their support)

Agreed. I even set it up already in [package.json](https://github.com/msaraiva/vscode-surface/blob/master/package.json#L7) :)

> How feasible/how much work would it take to add the Surface support to vscode-elixir-ls? (I really don't have a handle on the work involved)

The first version I created was actually a fork of `vscode-elixir-ls`. However, I decided to move it to a separated project so users that have other extensions installed could also use it.

> Is there a way to ensure that vscode-surface is discoverable to users using Surface (besides the surface or vscode-surface docs). VSCode has a nice prompt that comes up when you first open an Elixir file and don't have any extensions that handle .ex. Perhaps something similar could be added to vscode-elixir-ls that would suggest vscode-surface the first time you open a Surface file.

Sounds cool. However, this is the first extension I create for VS Code. I'm not sure how to do it. Yet :)

**Comment by msaraiva** [comment]
@axelson BTW, regarding:

> I'd be glad to add you to the publisher, although it may be a bit of a manual process involving their support

No problem. Just give some basic instructions. Otherwise, feel free to publish it if you want.

**Comment by axelson** [comment]
> The first version I created was actually a fork of vscode-elixir-ls. However, I decided to move it to a separated project so users that have other extensions installed could also use it.

That's a good point :+1: 

>>    I'd be glad to add you to the publisher, although it may be a bit of a manual process involving their support
>
> No problem. Just give some basic instructions. Otherwise, feel free to publish it if you want.

I'd rather not be responsible for another package :)

Can you run through https://code.visualstudio.com/api/working-with-extensions/publishing-extension and publish a test extension (just to be sure that everything is setup) and then give me the email associated with your microsoft account (you can send it to my email or as a PM on the elixir forum)

**Comment by msaraiva** [comment]
> Can you run through https://code.visualstudio.com/api/working-with-extensions/publishing-extension and publish a test extension (just to be sure that everything is setup) and then give me the email associated with your microsoft account (you can send it to my email or as a PM on the elixir forum)

@axelson sounds good. Can you please create a `vscode-surface` project under the `elixir-lsp` organization and give me write access? I tried to transfer the repo but I don't have permission for that :(

**Comment by axelson** [comment]
Okay, created `vscode-surface` and sent you an invite!

https://github.com/elixir-lsp/vscode-surface

**Comment by msaraiva** [comment]
@axelson awesome! I just sent you a DM with the email associated.

Thanks!

**Comment by msaraiva** [comment]
@axelson I managed to publish the extension under `msaraiva` organization. Everything is working fine. I can move the project to `elixir-lsp` in the future when they solve the "Invalid Domain" problem.

Here's the link: https://marketplace.visualstudio.com/items?itemName=msaraiva.surface

Thanks for your help!
