### ISSUE TITLE
[error] Task started from ElixirSense.Server.TCPServer terminating

### ISSUE THREAD

**Issue by Ajwah** [elixir-lsp/elixir_sense#83]
IDE: VScode
OS: MacOS

The following is an error I see in Developer Tools when I restart VSCode:
```
[ElixirSense] 13:22:09.105 [error] Task #PID<0.159.0> started from ElixirSense.Server.TCPServer terminating** (stop) exited in: GenServer.call(ElixirSense.Server.TCPServer.ConnectionHandlerSupervisor, {:start_task, [{:nonode@nohost, #PID<0.159.0>, #PID<0.159.0>}, [#PID<0.159.0>, #PID<0.158.0>], {:erlang, :apply, [#Function<1.131136907/0 in ElixirSense.Server.TCPServer.start_connection_handler/2>, []]}], nil, nil}, :infinity)    
** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started    (elixir) lib/gen_server.ex:999: GenServer.call/3    
/Users/kj/.vscode-insiders/extensions/mjmcloug.vscode-elixir-1.1.0/elixir_sense/lib/elixir_sense/server/tcp_server.ex:58: ElixirSense.Server.TCPServer.accept/2    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3Function: &ElixirSense.Server.TCPServer.listen/3    Args: ["unix", "localhost", "0"]ok:localhost:/tmp/elixir-sense-1581272529106882000.sock (at Socket.<anonymous> (/Users/kj/.vscode-insiders/extensions/mjmcloug.vscode-elixir-1.1.0/out/src/elixirSenseServerProcess.js:35:21))
```

**Comment by axelson** [comment]
What version of Elixir are you using in your project? This might be an issue with Elixir 1.10 support which would require a later version of ElixirSense than is packaged in https://github.com/fr1zle/vscode-elixir/

Can you try the "Elixir LS Fork" https://marketplace.visualstudio.com/items?itemName=elixir-lsp.elixir-ls instead?

**Comment by Ajwah** [comment]
Elixir version: Latest
I am using "Elixir LS Fork"

**Comment by lukaszsamson** [comment]
@Ajwah In your log I can see that you are using some other vscode extension `vscode-elixir-1.1.0` https://marketplace.visualstudio.com/items?itemName=mjmcloug.vscode-elixir.
vscode-elixir seems to be no longer maintained and uses a very old elixir_sense version.
Elixir LS Fork (https://marketplace.visualstudio.com/items?itemName=elixir-lsp.elixir-ls) is not even using ElixirSense.Server.TCPServer.
My guess is you have 2 extensions enabled and they interfere.
