### ISSUE TITLE
Unnecessary suggestions inside heredoc

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lsp/elixir_sense#88]
The following test is failing
```
  test "no completion inside docstring" do
    buffer = """
    defmodule MyModule do
      @moduledoc \"\"\"
      This is a module asd.
      \"\"\"
    end
    """

    assert [] == ElixirSense.suggestions(buffer, 3, 24)
  end
```
Suggestions are not aware that this is heredoc and are providing results for `asd.` subject.

**Comment by axelson** [comment]
I'm somewhat inclined to leave this as-is because sometimes suggestions within a moduledoc are helpful, especially when you're referencing a module that exists in the project. Although it can also be annoying at times since most of the suggestions will be incorrect.
