### ISSUE TITLE
Transfer ownership from msaraiva to elixir-lsp

### ISSUE THREAD

**Issue by msaraiva** [elixir-lsp/elixir_sense#90]
Original discussion started here: https://github.com/msaraiva/elixir_sense/issues/42#issuecomment-574903296

As already explained, I'll be glad to transfer the ownership. We just need to synchronize the steps to minimize the troubles we might have. Does [this](https://github.com/msaraiva/elixir_sense/issues/42#issuecomment-585392270) sound feasible?

**Comment by msaraiva** [comment]
@axelson should we still try this?

**Comment by axelson** [comment]
@msaraiva I think my preference would be to preserve the history (especially of issues) on both repositories. So maybe we could detach elixir-lsp/elixir_sense to make it its own root repository, similar to what we did for ElixirLS at https://github.com/elixir-lsp/elixir-ls/issues/310 How does that sound? We should probably do with https://github.com/elixir-lsp/vscode-elixir-ls/ as well.

**Comment by msaraiva** [comment]
@axelson sounds good to me! Is my intervention required in any way?

**Comment by axelson** [comment]
Nope. And I just sent in the request.

**Comment by axelson** [comment]
Okay, this is now complete!

**Comment by msaraiva** [comment]
Awesome!
