### ISSUE TITLE
Refactor suggestions engine

### ISSUE THREAD

**Issue by msaraiva** [elixir-lsp/elixir_sense#98]
Currently, the logic we have in [ElixirSense.Providers.Suggestion](https://github.com/elixir-lsp/elixir_sense/blob/master/lib/elixir_sense/providers/suggestion.ex) is way too complex and hard to maintain. For instance if we want to restrict the list of suggestions based on the context, we need to write that logic for each different case we need.

I started to refactor the code so we can have a main reducer going through a list of producers. Each producer returns a set of suggestions that will be added to the final list. A producer can also inform if the reducer should continue to collect more suggestions or if the list provided is already the final list.

One problem I've found so far is handling the `hint` suggestion. Currently, the hint suggestion is generated along with variables, attributes, variable fields, functions, macros and modules, all inside `ElixirSense.Providers.Suggestion.Complete.complete/2`. If I want to be able to selectively show/hide individual groups of suggestions, I need to have a way to split them into groups. That's possible with the current implementation by naively using `Enum.group_by/2`. The problem is that the hint item, as far as I understood, is built while retrieving all those suggestions. If I remove any of them, the hint might become invalid.

So I have a question: Is the hint suggestion actually being used by any editor?  Can't we just drop it out of the list and get rid of all the complexity involved? I took a look at `elixir-ls` code and I couldn't find where it's being used. It's just ignored.

@lukaszsamson in case we can't drop the hint suggestion, do you think it would be feasible to extract the related logic so we could apply it only after we have the final list? I've noticed you do something similar using the `Hint.combine/2` function, however, I couldn't find a way to use it with the existing suggestions already returned by `Complete.complete/2`.

**Comment by lukaszsamson** [comment]
Well, I don't really know about other currently maintained users of elixir_sense, I'm only certain that elisir-ls does not use it. When I introduced the `Hint` module I was mainly concerned with not introducing breaking changes but maybe we should. It's a relict from `iex` REPL and it's not that useful for code editors. In particular the LSP protocol does not define any hints and clients are free to build them from completion items. Removing it would make `Complete` module simpler and more compatible with other providers. If we decide to keep it, it would be easy to generate it as a last step as the algorithm is rather simple - it just takes the longest common prefix.

**Comment by msaraiva** [comment]
Awesome! I agree. I think there's no practical use for it when working with editors.

Let's just remove the damn thing!

@axelson in case you know any maintainers that might still need this feature, please ping them so they can have a last opportunity to change our mind :)

**Comment by axelson** [comment]
I don't know of any so I think you should go ahead 👍
